// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rins.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_rins_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_rins_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021011 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_rins_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_rins_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_rins_2eproto;
namespace rins {
class GetHostRequest;
struct GetHostRequestDefaultTypeInternal;
extern GetHostRequestDefaultTypeInternal _GetHostRequest_default_instance_;
class GetHostResponse;
struct GetHostResponseDefaultTypeInternal;
extern GetHostResponseDefaultTypeInternal _GetHostResponse_default_instance_;
class GetRouteRequest;
struct GetRouteRequestDefaultTypeInternal;
extern GetRouteRequestDefaultTypeInternal _GetRouteRequest_default_instance_;
class GetRouteResponse;
struct GetRouteResponseDefaultTypeInternal;
extern GetRouteResponseDefaultTypeInternal _GetRouteResponse_default_instance_;
class HostCallResult;
struct HostCallResultDefaultTypeInternal;
extern HostCallResultDefaultTypeInternal _HostCallResult_default_instance_;
class HostInfo;
struct HostInfoDefaultTypeInternal;
extern HostInfoDefaultTypeInternal _HostInfo_default_instance_;
class ReportStatusRequest;
struct ReportStatusRequestDefaultTypeInternal;
extern ReportStatusRequestDefaultTypeInternal _ReportStatusRequest_default_instance_;
}  // namespace rins
PROTOBUF_NAMESPACE_OPEN
template<> ::rins::GetHostRequest* Arena::CreateMaybeMessage<::rins::GetHostRequest>(Arena*);
template<> ::rins::GetHostResponse* Arena::CreateMaybeMessage<::rins::GetHostResponse>(Arena*);
template<> ::rins::GetRouteRequest* Arena::CreateMaybeMessage<::rins::GetRouteRequest>(Arena*);
template<> ::rins::GetRouteResponse* Arena::CreateMaybeMessage<::rins::GetRouteResponse>(Arena*);
template<> ::rins::HostCallResult* Arena::CreateMaybeMessage<::rins::HostCallResult>(Arena*);
template<> ::rins::HostInfo* Arena::CreateMaybeMessage<::rins::HostInfo>(Arena*);
template<> ::rins::ReportStatusRequest* Arena::CreateMaybeMessage<::rins::ReportStatusRequest>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rins {

enum MessageID : int {
  ID_UNKNOW = 0,
  ID_GetRouteRequest = 1,
  ID_GetRouteResponse = 2,
  ID_ReportStatusRequest = 3,
  ID_GetHostRequest = 4,
  ID_GetHostResponse = 5,
  MessageID_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  MessageID_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool MessageID_IsValid(int value);
constexpr MessageID MessageID_MIN = ID_UNKNOW;
constexpr MessageID MessageID_MAX = ID_GetHostResponse;
constexpr int MessageID_ARRAYSIZE = MessageID_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* MessageID_descriptor();
template<typename T>
inline const std::string& MessageID_Name(T enum_t_value) {
  static_assert(::std::is_same<T, MessageID>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function MessageID_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    MessageID_descriptor(), enum_t_value);
}
inline bool MessageID_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, MessageID* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<MessageID>(
    MessageID_descriptor(), name, value);
}
enum RinsRetCode : int {
  RET_SUCC = 0,
  RET_OVERLOAD = 1,
  RET_SYSTEM_ERROR = 2,
  RET_NOEXIST = 3,
  RinsRetCode_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  RinsRetCode_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool RinsRetCode_IsValid(int value);
constexpr RinsRetCode RinsRetCode_MIN = RET_SUCC;
constexpr RinsRetCode RinsRetCode_MAX = RET_NOEXIST;
constexpr int RinsRetCode_ARRAYSIZE = RinsRetCode_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* RinsRetCode_descriptor();
template<typename T>
inline const std::string& RinsRetCode_Name(T enum_t_value) {
  static_assert(::std::is_same<T, RinsRetCode>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function RinsRetCode_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    RinsRetCode_descriptor(), enum_t_value);
}
inline bool RinsRetCode_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, RinsRetCode* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<RinsRetCode>(
    RinsRetCode_descriptor(), name, value);
}
// ===================================================================

class HostInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rins.HostInfo) */ {
 public:
  inline HostInfo() : HostInfo(nullptr) {}
  ~HostInfo() override;
  explicit PROTOBUF_CONSTEXPR HostInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HostInfo(const HostInfo& from);
  HostInfo(HostInfo&& from) noexcept
    : HostInfo() {
    *this = ::std::move(from);
  }

  inline HostInfo& operator=(const HostInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline HostInfo& operator=(HostInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HostInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const HostInfo* internal_default_instance() {
    return reinterpret_cast<const HostInfo*>(
               &_HostInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(HostInfo& a, HostInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(HostInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HostInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HostInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HostInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HostInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HostInfo& from) {
    HostInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HostInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rins.HostInfo";
  }
  protected:
  explicit HostInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
  };
  // int32 ip = 1;
  void clear_ip();
  int32_t ip() const;
  void set_ip(int32_t value);
  private:
  int32_t _internal_ip() const;
  void _internal_set_ip(int32_t value);
  public:

  // int32 port = 2;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rins.HostInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t ip_;
    int32_t port_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rins_2eproto;
};
// -------------------------------------------------------------------

class GetRouteRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rins.GetRouteRequest) */ {
 public:
  inline GetRouteRequest() : GetRouteRequest(nullptr) {}
  ~GetRouteRequest() override;
  explicit PROTOBUF_CONSTEXPR GetRouteRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetRouteRequest(const GetRouteRequest& from);
  GetRouteRequest(GetRouteRequest&& from) noexcept
    : GetRouteRequest() {
    *this = ::std::move(from);
  }

  inline GetRouteRequest& operator=(const GetRouteRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetRouteRequest& operator=(GetRouteRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetRouteRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetRouteRequest* internal_default_instance() {
    return reinterpret_cast<const GetRouteRequest*>(
               &_GetRouteRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(GetRouteRequest& a, GetRouteRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetRouteRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetRouteRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetRouteRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetRouteRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetRouteRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetRouteRequest& from) {
    GetRouteRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetRouteRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rins.GetRouteRequest";
  }
  protected:
  explicit GetRouteRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModidFieldNumber = 1,
    kCmdidFieldNumber = 2,
  };
  // int32 modid = 1;
  void clear_modid();
  int32_t modid() const;
  void set_modid(int32_t value);
  private:
  int32_t _internal_modid() const;
  void _internal_set_modid(int32_t value);
  public:

  // int32 cmdid = 2;
  void clear_cmdid();
  int32_t cmdid() const;
  void set_cmdid(int32_t value);
  private:
  int32_t _internal_cmdid() const;
  void _internal_set_cmdid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rins.GetRouteRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t modid_;
    int32_t cmdid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rins_2eproto;
};
// -------------------------------------------------------------------

class GetRouteResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rins.GetRouteResponse) */ {
 public:
  inline GetRouteResponse() : GetRouteResponse(nullptr) {}
  ~GetRouteResponse() override;
  explicit PROTOBUF_CONSTEXPR GetRouteResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetRouteResponse(const GetRouteResponse& from);
  GetRouteResponse(GetRouteResponse&& from) noexcept
    : GetRouteResponse() {
    *this = ::std::move(from);
  }

  inline GetRouteResponse& operator=(const GetRouteResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetRouteResponse& operator=(GetRouteResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetRouteResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetRouteResponse* internal_default_instance() {
    return reinterpret_cast<const GetRouteResponse*>(
               &_GetRouteResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetRouteResponse& a, GetRouteResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetRouteResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetRouteResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetRouteResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetRouteResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetRouteResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetRouteResponse& from) {
    GetRouteResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetRouteResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rins.GetRouteResponse";
  }
  protected:
  explicit GetRouteResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHostFieldNumber = 3,
    kModidFieldNumber = 1,
    kCmdidFieldNumber = 2,
  };
  // repeated .rins.HostInfo host = 3;
  int host_size() const;
  private:
  int _internal_host_size() const;
  public:
  void clear_host();
  ::rins::HostInfo* mutable_host(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostInfo >*
      mutable_host();
  private:
  const ::rins::HostInfo& _internal_host(int index) const;
  ::rins::HostInfo* _internal_add_host();
  public:
  const ::rins::HostInfo& host(int index) const;
  ::rins::HostInfo* add_host();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostInfo >&
      host() const;

  // int32 modid = 1;
  void clear_modid();
  int32_t modid() const;
  void set_modid(int32_t value);
  private:
  int32_t _internal_modid() const;
  void _internal_set_modid(int32_t value);
  public:

  // int32 cmdid = 2;
  void clear_cmdid();
  int32_t cmdid() const;
  void set_cmdid(int32_t value);
  private:
  int32_t _internal_cmdid() const;
  void _internal_set_cmdid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rins.GetRouteResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostInfo > host_;
    int32_t modid_;
    int32_t cmdid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rins_2eproto;
};
// -------------------------------------------------------------------

class HostCallResult final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rins.HostCallResult) */ {
 public:
  inline HostCallResult() : HostCallResult(nullptr) {}
  ~HostCallResult() override;
  explicit PROTOBUF_CONSTEXPR HostCallResult(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  HostCallResult(const HostCallResult& from);
  HostCallResult(HostCallResult&& from) noexcept
    : HostCallResult() {
    *this = ::std::move(from);
  }

  inline HostCallResult& operator=(const HostCallResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline HostCallResult& operator=(HostCallResult&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const HostCallResult& default_instance() {
    return *internal_default_instance();
  }
  static inline const HostCallResult* internal_default_instance() {
    return reinterpret_cast<const HostCallResult*>(
               &_HostCallResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(HostCallResult& a, HostCallResult& b) {
    a.Swap(&b);
  }
  inline void Swap(HostCallResult* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(HostCallResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  HostCallResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<HostCallResult>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const HostCallResult& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const HostCallResult& from) {
    HostCallResult::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(HostCallResult* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rins.HostCallResult";
  }
  protected:
  explicit HostCallResult(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIpFieldNumber = 1,
    kPortFieldNumber = 2,
    kSuccFieldNumber = 3,
    kErrFieldNumber = 4,
    kOverloadFieldNumber = 5,
  };
  // int32 ip = 1;
  void clear_ip();
  int32_t ip() const;
  void set_ip(int32_t value);
  private:
  int32_t _internal_ip() const;
  void _internal_set_ip(int32_t value);
  public:

  // int32 port = 2;
  void clear_port();
  int32_t port() const;
  void set_port(int32_t value);
  private:
  int32_t _internal_port() const;
  void _internal_set_port(int32_t value);
  public:

  // uint32 succ = 3;
  void clear_succ();
  uint32_t succ() const;
  void set_succ(uint32_t value);
  private:
  uint32_t _internal_succ() const;
  void _internal_set_succ(uint32_t value);
  public:

  // uint32 err = 4;
  void clear_err();
  uint32_t err() const;
  void set_err(uint32_t value);
  private:
  uint32_t _internal_err() const;
  void _internal_set_err(uint32_t value);
  public:

  // bool overload = 5;
  void clear_overload();
  bool overload() const;
  void set_overload(bool value);
  private:
  bool _internal_overload() const;
  void _internal_set_overload(bool value);
  public:

  // @@protoc_insertion_point(class_scope:rins.HostCallResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t ip_;
    int32_t port_;
    uint32_t succ_;
    uint32_t err_;
    bool overload_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rins_2eproto;
};
// -------------------------------------------------------------------

class ReportStatusRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rins.ReportStatusRequest) */ {
 public:
  inline ReportStatusRequest() : ReportStatusRequest(nullptr) {}
  ~ReportStatusRequest() override;
  explicit PROTOBUF_CONSTEXPR ReportStatusRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReportStatusRequest(const ReportStatusRequest& from);
  ReportStatusRequest(ReportStatusRequest&& from) noexcept
    : ReportStatusRequest() {
    *this = ::std::move(from);
  }

  inline ReportStatusRequest& operator=(const ReportStatusRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReportStatusRequest& operator=(ReportStatusRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReportStatusRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReportStatusRequest* internal_default_instance() {
    return reinterpret_cast<const ReportStatusRequest*>(
               &_ReportStatusRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ReportStatusRequest& a, ReportStatusRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReportStatusRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReportStatusRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReportStatusRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReportStatusRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReportStatusRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ReportStatusRequest& from) {
    ReportStatusRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReportStatusRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rins.ReportStatusRequest";
  }
  protected:
  explicit ReportStatusRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kResultsFieldNumber = 4,
    kModidFieldNumber = 1,
    kCmdidFieldNumber = 2,
    kCallerFieldNumber = 3,
    kTimestampFieldNumber = 5,
  };
  // repeated .rins.HostCallResult results = 4;
  int results_size() const;
  private:
  int _internal_results_size() const;
  public:
  void clear_results();
  ::rins::HostCallResult* mutable_results(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostCallResult >*
      mutable_results();
  private:
  const ::rins::HostCallResult& _internal_results(int index) const;
  ::rins::HostCallResult* _internal_add_results();
  public:
  const ::rins::HostCallResult& results(int index) const;
  ::rins::HostCallResult* add_results();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostCallResult >&
      results() const;

  // int32 modid = 1;
  void clear_modid();
  int32_t modid() const;
  void set_modid(int32_t value);
  private:
  int32_t _internal_modid() const;
  void _internal_set_modid(int32_t value);
  public:

  // int32 cmdid = 2;
  void clear_cmdid();
  int32_t cmdid() const;
  void set_cmdid(int32_t value);
  private:
  int32_t _internal_cmdid() const;
  void _internal_set_cmdid(int32_t value);
  public:

  // int32 caller = 3;
  void clear_caller();
  int32_t caller() const;
  void set_caller(int32_t value);
  private:
  int32_t _internal_caller() const;
  void _internal_set_caller(int32_t value);
  public:

  // uint32 timestamp = 5;
  void clear_timestamp();
  uint32_t timestamp() const;
  void set_timestamp(uint32_t value);
  private:
  uint32_t _internal_timestamp() const;
  void _internal_set_timestamp(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rins.ReportStatusRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostCallResult > results_;
    int32_t modid_;
    int32_t cmdid_;
    int32_t caller_;
    uint32_t timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rins_2eproto;
};
// -------------------------------------------------------------------

class GetHostRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rins.GetHostRequest) */ {
 public:
  inline GetHostRequest() : GetHostRequest(nullptr) {}
  ~GetHostRequest() override;
  explicit PROTOBUF_CONSTEXPR GetHostRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetHostRequest(const GetHostRequest& from);
  GetHostRequest(GetHostRequest&& from) noexcept
    : GetHostRequest() {
    *this = ::std::move(from);
  }

  inline GetHostRequest& operator=(const GetHostRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetHostRequest& operator=(GetHostRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetHostRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetHostRequest* internal_default_instance() {
    return reinterpret_cast<const GetHostRequest*>(
               &_GetHostRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(GetHostRequest& a, GetHostRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(GetHostRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetHostRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetHostRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetHostRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetHostRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetHostRequest& from) {
    GetHostRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetHostRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rins.GetHostRequest";
  }
  protected:
  explicit GetHostRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSeqFieldNumber = 1,
    kModidFieldNumber = 2,
    kCmdidFieldNumber = 3,
  };
  // uint32 seq = 1;
  void clear_seq();
  uint32_t seq() const;
  void set_seq(uint32_t value);
  private:
  uint32_t _internal_seq() const;
  void _internal_set_seq(uint32_t value);
  public:

  // int32 modid = 2;
  void clear_modid();
  int32_t modid() const;
  void set_modid(int32_t value);
  private:
  int32_t _internal_modid() const;
  void _internal_set_modid(int32_t value);
  public:

  // int32 cmdid = 3;
  void clear_cmdid();
  int32_t cmdid() const;
  void set_cmdid(int32_t value);
  private:
  int32_t _internal_cmdid() const;
  void _internal_set_cmdid(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rins.GetHostRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint32_t seq_;
    int32_t modid_;
    int32_t cmdid_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rins_2eproto;
};
// -------------------------------------------------------------------

class GetHostResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rins.GetHostResponse) */ {
 public:
  inline GetHostResponse() : GetHostResponse(nullptr) {}
  ~GetHostResponse() override;
  explicit PROTOBUF_CONSTEXPR GetHostResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetHostResponse(const GetHostResponse& from);
  GetHostResponse(GetHostResponse&& from) noexcept
    : GetHostResponse() {
    *this = ::std::move(from);
  }

  inline GetHostResponse& operator=(const GetHostResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetHostResponse& operator=(GetHostResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetHostResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetHostResponse* internal_default_instance() {
    return reinterpret_cast<const GetHostResponse*>(
               &_GetHostResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(GetHostResponse& a, GetHostResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetHostResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetHostResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetHostResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetHostResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetHostResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const GetHostResponse& from) {
    GetHostResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetHostResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rins.GetHostResponse";
  }
  protected:
  explicit GetHostResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHostFieldNumber = 5,
    kSeqFieldNumber = 1,
    kModidFieldNumber = 2,
    kCmdidFieldNumber = 3,
    kRetcodeFieldNumber = 4,
  };
  // .rins.HostInfo host = 5;
  bool has_host() const;
  private:
  bool _internal_has_host() const;
  public:
  void clear_host();
  const ::rins::HostInfo& host() const;
  PROTOBUF_NODISCARD ::rins::HostInfo* release_host();
  ::rins::HostInfo* mutable_host();
  void set_allocated_host(::rins::HostInfo* host);
  private:
  const ::rins::HostInfo& _internal_host() const;
  ::rins::HostInfo* _internal_mutable_host();
  public:
  void unsafe_arena_set_allocated_host(
      ::rins::HostInfo* host);
  ::rins::HostInfo* unsafe_arena_release_host();

  // uint32 seq = 1;
  void clear_seq();
  uint32_t seq() const;
  void set_seq(uint32_t value);
  private:
  uint32_t _internal_seq() const;
  void _internal_set_seq(uint32_t value);
  public:

  // int32 modid = 2;
  void clear_modid();
  int32_t modid() const;
  void set_modid(int32_t value);
  private:
  int32_t _internal_modid() const;
  void _internal_set_modid(int32_t value);
  public:

  // int32 cmdid = 3;
  void clear_cmdid();
  int32_t cmdid() const;
  void set_cmdid(int32_t value);
  private:
  int32_t _internal_cmdid() const;
  void _internal_set_cmdid(int32_t value);
  public:

  // int32 retcode = 4;
  void clear_retcode();
  int32_t retcode() const;
  void set_retcode(int32_t value);
  private:
  int32_t _internal_retcode() const;
  void _internal_set_retcode(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:rins.GetHostResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::rins::HostInfo* host_;
    uint32_t seq_;
    int32_t modid_;
    int32_t cmdid_;
    int32_t retcode_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_rins_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// HostInfo

// int32 ip = 1;
inline void HostInfo::clear_ip() {
  _impl_.ip_ = 0;
}
inline int32_t HostInfo::_internal_ip() const {
  return _impl_.ip_;
}
inline int32_t HostInfo::ip() const {
  // @@protoc_insertion_point(field_get:rins.HostInfo.ip)
  return _internal_ip();
}
inline void HostInfo::_internal_set_ip(int32_t value) {
  
  _impl_.ip_ = value;
}
inline void HostInfo::set_ip(int32_t value) {
  _internal_set_ip(value);
  // @@protoc_insertion_point(field_set:rins.HostInfo.ip)
}

// int32 port = 2;
inline void HostInfo::clear_port() {
  _impl_.port_ = 0;
}
inline int32_t HostInfo::_internal_port() const {
  return _impl_.port_;
}
inline int32_t HostInfo::port() const {
  // @@protoc_insertion_point(field_get:rins.HostInfo.port)
  return _internal_port();
}
inline void HostInfo::_internal_set_port(int32_t value) {
  
  _impl_.port_ = value;
}
inline void HostInfo::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:rins.HostInfo.port)
}

// -------------------------------------------------------------------

// GetRouteRequest

// int32 modid = 1;
inline void GetRouteRequest::clear_modid() {
  _impl_.modid_ = 0;
}
inline int32_t GetRouteRequest::_internal_modid() const {
  return _impl_.modid_;
}
inline int32_t GetRouteRequest::modid() const {
  // @@protoc_insertion_point(field_get:rins.GetRouteRequest.modid)
  return _internal_modid();
}
inline void GetRouteRequest::_internal_set_modid(int32_t value) {
  
  _impl_.modid_ = value;
}
inline void GetRouteRequest::set_modid(int32_t value) {
  _internal_set_modid(value);
  // @@protoc_insertion_point(field_set:rins.GetRouteRequest.modid)
}

// int32 cmdid = 2;
inline void GetRouteRequest::clear_cmdid() {
  _impl_.cmdid_ = 0;
}
inline int32_t GetRouteRequest::_internal_cmdid() const {
  return _impl_.cmdid_;
}
inline int32_t GetRouteRequest::cmdid() const {
  // @@protoc_insertion_point(field_get:rins.GetRouteRequest.cmdid)
  return _internal_cmdid();
}
inline void GetRouteRequest::_internal_set_cmdid(int32_t value) {
  
  _impl_.cmdid_ = value;
}
inline void GetRouteRequest::set_cmdid(int32_t value) {
  _internal_set_cmdid(value);
  // @@protoc_insertion_point(field_set:rins.GetRouteRequest.cmdid)
}

// -------------------------------------------------------------------

// GetRouteResponse

// int32 modid = 1;
inline void GetRouteResponse::clear_modid() {
  _impl_.modid_ = 0;
}
inline int32_t GetRouteResponse::_internal_modid() const {
  return _impl_.modid_;
}
inline int32_t GetRouteResponse::modid() const {
  // @@protoc_insertion_point(field_get:rins.GetRouteResponse.modid)
  return _internal_modid();
}
inline void GetRouteResponse::_internal_set_modid(int32_t value) {
  
  _impl_.modid_ = value;
}
inline void GetRouteResponse::set_modid(int32_t value) {
  _internal_set_modid(value);
  // @@protoc_insertion_point(field_set:rins.GetRouteResponse.modid)
}

// int32 cmdid = 2;
inline void GetRouteResponse::clear_cmdid() {
  _impl_.cmdid_ = 0;
}
inline int32_t GetRouteResponse::_internal_cmdid() const {
  return _impl_.cmdid_;
}
inline int32_t GetRouteResponse::cmdid() const {
  // @@protoc_insertion_point(field_get:rins.GetRouteResponse.cmdid)
  return _internal_cmdid();
}
inline void GetRouteResponse::_internal_set_cmdid(int32_t value) {
  
  _impl_.cmdid_ = value;
}
inline void GetRouteResponse::set_cmdid(int32_t value) {
  _internal_set_cmdid(value);
  // @@protoc_insertion_point(field_set:rins.GetRouteResponse.cmdid)
}

// repeated .rins.HostInfo host = 3;
inline int GetRouteResponse::_internal_host_size() const {
  return _impl_.host_.size();
}
inline int GetRouteResponse::host_size() const {
  return _internal_host_size();
}
inline void GetRouteResponse::clear_host() {
  _impl_.host_.Clear();
}
inline ::rins::HostInfo* GetRouteResponse::mutable_host(int index) {
  // @@protoc_insertion_point(field_mutable:rins.GetRouteResponse.host)
  return _impl_.host_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostInfo >*
GetRouteResponse::mutable_host() {
  // @@protoc_insertion_point(field_mutable_list:rins.GetRouteResponse.host)
  return &_impl_.host_;
}
inline const ::rins::HostInfo& GetRouteResponse::_internal_host(int index) const {
  return _impl_.host_.Get(index);
}
inline const ::rins::HostInfo& GetRouteResponse::host(int index) const {
  // @@protoc_insertion_point(field_get:rins.GetRouteResponse.host)
  return _internal_host(index);
}
inline ::rins::HostInfo* GetRouteResponse::_internal_add_host() {
  return _impl_.host_.Add();
}
inline ::rins::HostInfo* GetRouteResponse::add_host() {
  ::rins::HostInfo* _add = _internal_add_host();
  // @@protoc_insertion_point(field_add:rins.GetRouteResponse.host)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostInfo >&
GetRouteResponse::host() const {
  // @@protoc_insertion_point(field_list:rins.GetRouteResponse.host)
  return _impl_.host_;
}

// -------------------------------------------------------------------

// HostCallResult

// int32 ip = 1;
inline void HostCallResult::clear_ip() {
  _impl_.ip_ = 0;
}
inline int32_t HostCallResult::_internal_ip() const {
  return _impl_.ip_;
}
inline int32_t HostCallResult::ip() const {
  // @@protoc_insertion_point(field_get:rins.HostCallResult.ip)
  return _internal_ip();
}
inline void HostCallResult::_internal_set_ip(int32_t value) {
  
  _impl_.ip_ = value;
}
inline void HostCallResult::set_ip(int32_t value) {
  _internal_set_ip(value);
  // @@protoc_insertion_point(field_set:rins.HostCallResult.ip)
}

// int32 port = 2;
inline void HostCallResult::clear_port() {
  _impl_.port_ = 0;
}
inline int32_t HostCallResult::_internal_port() const {
  return _impl_.port_;
}
inline int32_t HostCallResult::port() const {
  // @@protoc_insertion_point(field_get:rins.HostCallResult.port)
  return _internal_port();
}
inline void HostCallResult::_internal_set_port(int32_t value) {
  
  _impl_.port_ = value;
}
inline void HostCallResult::set_port(int32_t value) {
  _internal_set_port(value);
  // @@protoc_insertion_point(field_set:rins.HostCallResult.port)
}

// uint32 succ = 3;
inline void HostCallResult::clear_succ() {
  _impl_.succ_ = 0u;
}
inline uint32_t HostCallResult::_internal_succ() const {
  return _impl_.succ_;
}
inline uint32_t HostCallResult::succ() const {
  // @@protoc_insertion_point(field_get:rins.HostCallResult.succ)
  return _internal_succ();
}
inline void HostCallResult::_internal_set_succ(uint32_t value) {
  
  _impl_.succ_ = value;
}
inline void HostCallResult::set_succ(uint32_t value) {
  _internal_set_succ(value);
  // @@protoc_insertion_point(field_set:rins.HostCallResult.succ)
}

// uint32 err = 4;
inline void HostCallResult::clear_err() {
  _impl_.err_ = 0u;
}
inline uint32_t HostCallResult::_internal_err() const {
  return _impl_.err_;
}
inline uint32_t HostCallResult::err() const {
  // @@protoc_insertion_point(field_get:rins.HostCallResult.err)
  return _internal_err();
}
inline void HostCallResult::_internal_set_err(uint32_t value) {
  
  _impl_.err_ = value;
}
inline void HostCallResult::set_err(uint32_t value) {
  _internal_set_err(value);
  // @@protoc_insertion_point(field_set:rins.HostCallResult.err)
}

// bool overload = 5;
inline void HostCallResult::clear_overload() {
  _impl_.overload_ = false;
}
inline bool HostCallResult::_internal_overload() const {
  return _impl_.overload_;
}
inline bool HostCallResult::overload() const {
  // @@protoc_insertion_point(field_get:rins.HostCallResult.overload)
  return _internal_overload();
}
inline void HostCallResult::_internal_set_overload(bool value) {
  
  _impl_.overload_ = value;
}
inline void HostCallResult::set_overload(bool value) {
  _internal_set_overload(value);
  // @@protoc_insertion_point(field_set:rins.HostCallResult.overload)
}

// -------------------------------------------------------------------

// ReportStatusRequest

// int32 modid = 1;
inline void ReportStatusRequest::clear_modid() {
  _impl_.modid_ = 0;
}
inline int32_t ReportStatusRequest::_internal_modid() const {
  return _impl_.modid_;
}
inline int32_t ReportStatusRequest::modid() const {
  // @@protoc_insertion_point(field_get:rins.ReportStatusRequest.modid)
  return _internal_modid();
}
inline void ReportStatusRequest::_internal_set_modid(int32_t value) {
  
  _impl_.modid_ = value;
}
inline void ReportStatusRequest::set_modid(int32_t value) {
  _internal_set_modid(value);
  // @@protoc_insertion_point(field_set:rins.ReportStatusRequest.modid)
}

// int32 cmdid = 2;
inline void ReportStatusRequest::clear_cmdid() {
  _impl_.cmdid_ = 0;
}
inline int32_t ReportStatusRequest::_internal_cmdid() const {
  return _impl_.cmdid_;
}
inline int32_t ReportStatusRequest::cmdid() const {
  // @@protoc_insertion_point(field_get:rins.ReportStatusRequest.cmdid)
  return _internal_cmdid();
}
inline void ReportStatusRequest::_internal_set_cmdid(int32_t value) {
  
  _impl_.cmdid_ = value;
}
inline void ReportStatusRequest::set_cmdid(int32_t value) {
  _internal_set_cmdid(value);
  // @@protoc_insertion_point(field_set:rins.ReportStatusRequest.cmdid)
}

// int32 caller = 3;
inline void ReportStatusRequest::clear_caller() {
  _impl_.caller_ = 0;
}
inline int32_t ReportStatusRequest::_internal_caller() const {
  return _impl_.caller_;
}
inline int32_t ReportStatusRequest::caller() const {
  // @@protoc_insertion_point(field_get:rins.ReportStatusRequest.caller)
  return _internal_caller();
}
inline void ReportStatusRequest::_internal_set_caller(int32_t value) {
  
  _impl_.caller_ = value;
}
inline void ReportStatusRequest::set_caller(int32_t value) {
  _internal_set_caller(value);
  // @@protoc_insertion_point(field_set:rins.ReportStatusRequest.caller)
}

// repeated .rins.HostCallResult results = 4;
inline int ReportStatusRequest::_internal_results_size() const {
  return _impl_.results_.size();
}
inline int ReportStatusRequest::results_size() const {
  return _internal_results_size();
}
inline void ReportStatusRequest::clear_results() {
  _impl_.results_.Clear();
}
inline ::rins::HostCallResult* ReportStatusRequest::mutable_results(int index) {
  // @@protoc_insertion_point(field_mutable:rins.ReportStatusRequest.results)
  return _impl_.results_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostCallResult >*
ReportStatusRequest::mutable_results() {
  // @@protoc_insertion_point(field_mutable_list:rins.ReportStatusRequest.results)
  return &_impl_.results_;
}
inline const ::rins::HostCallResult& ReportStatusRequest::_internal_results(int index) const {
  return _impl_.results_.Get(index);
}
inline const ::rins::HostCallResult& ReportStatusRequest::results(int index) const {
  // @@protoc_insertion_point(field_get:rins.ReportStatusRequest.results)
  return _internal_results(index);
}
inline ::rins::HostCallResult* ReportStatusRequest::_internal_add_results() {
  return _impl_.results_.Add();
}
inline ::rins::HostCallResult* ReportStatusRequest::add_results() {
  ::rins::HostCallResult* _add = _internal_add_results();
  // @@protoc_insertion_point(field_add:rins.ReportStatusRequest.results)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::rins::HostCallResult >&
ReportStatusRequest::results() const {
  // @@protoc_insertion_point(field_list:rins.ReportStatusRequest.results)
  return _impl_.results_;
}

// uint32 timestamp = 5;
inline void ReportStatusRequest::clear_timestamp() {
  _impl_.timestamp_ = 0u;
}
inline uint32_t ReportStatusRequest::_internal_timestamp() const {
  return _impl_.timestamp_;
}
inline uint32_t ReportStatusRequest::timestamp() const {
  // @@protoc_insertion_point(field_get:rins.ReportStatusRequest.timestamp)
  return _internal_timestamp();
}
inline void ReportStatusRequest::_internal_set_timestamp(uint32_t value) {
  
  _impl_.timestamp_ = value;
}
inline void ReportStatusRequest::set_timestamp(uint32_t value) {
  _internal_set_timestamp(value);
  // @@protoc_insertion_point(field_set:rins.ReportStatusRequest.timestamp)
}

// -------------------------------------------------------------------

// GetHostRequest

// uint32 seq = 1;
inline void GetHostRequest::clear_seq() {
  _impl_.seq_ = 0u;
}
inline uint32_t GetHostRequest::_internal_seq() const {
  return _impl_.seq_;
}
inline uint32_t GetHostRequest::seq() const {
  // @@protoc_insertion_point(field_get:rins.GetHostRequest.seq)
  return _internal_seq();
}
inline void GetHostRequest::_internal_set_seq(uint32_t value) {
  
  _impl_.seq_ = value;
}
inline void GetHostRequest::set_seq(uint32_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:rins.GetHostRequest.seq)
}

// int32 modid = 2;
inline void GetHostRequest::clear_modid() {
  _impl_.modid_ = 0;
}
inline int32_t GetHostRequest::_internal_modid() const {
  return _impl_.modid_;
}
inline int32_t GetHostRequest::modid() const {
  // @@protoc_insertion_point(field_get:rins.GetHostRequest.modid)
  return _internal_modid();
}
inline void GetHostRequest::_internal_set_modid(int32_t value) {
  
  _impl_.modid_ = value;
}
inline void GetHostRequest::set_modid(int32_t value) {
  _internal_set_modid(value);
  // @@protoc_insertion_point(field_set:rins.GetHostRequest.modid)
}

// int32 cmdid = 3;
inline void GetHostRequest::clear_cmdid() {
  _impl_.cmdid_ = 0;
}
inline int32_t GetHostRequest::_internal_cmdid() const {
  return _impl_.cmdid_;
}
inline int32_t GetHostRequest::cmdid() const {
  // @@protoc_insertion_point(field_get:rins.GetHostRequest.cmdid)
  return _internal_cmdid();
}
inline void GetHostRequest::_internal_set_cmdid(int32_t value) {
  
  _impl_.cmdid_ = value;
}
inline void GetHostRequest::set_cmdid(int32_t value) {
  _internal_set_cmdid(value);
  // @@protoc_insertion_point(field_set:rins.GetHostRequest.cmdid)
}

// -------------------------------------------------------------------

// GetHostResponse

// uint32 seq = 1;
inline void GetHostResponse::clear_seq() {
  _impl_.seq_ = 0u;
}
inline uint32_t GetHostResponse::_internal_seq() const {
  return _impl_.seq_;
}
inline uint32_t GetHostResponse::seq() const {
  // @@protoc_insertion_point(field_get:rins.GetHostResponse.seq)
  return _internal_seq();
}
inline void GetHostResponse::_internal_set_seq(uint32_t value) {
  
  _impl_.seq_ = value;
}
inline void GetHostResponse::set_seq(uint32_t value) {
  _internal_set_seq(value);
  // @@protoc_insertion_point(field_set:rins.GetHostResponse.seq)
}

// int32 modid = 2;
inline void GetHostResponse::clear_modid() {
  _impl_.modid_ = 0;
}
inline int32_t GetHostResponse::_internal_modid() const {
  return _impl_.modid_;
}
inline int32_t GetHostResponse::modid() const {
  // @@protoc_insertion_point(field_get:rins.GetHostResponse.modid)
  return _internal_modid();
}
inline void GetHostResponse::_internal_set_modid(int32_t value) {
  
  _impl_.modid_ = value;
}
inline void GetHostResponse::set_modid(int32_t value) {
  _internal_set_modid(value);
  // @@protoc_insertion_point(field_set:rins.GetHostResponse.modid)
}

// int32 cmdid = 3;
inline void GetHostResponse::clear_cmdid() {
  _impl_.cmdid_ = 0;
}
inline int32_t GetHostResponse::_internal_cmdid() const {
  return _impl_.cmdid_;
}
inline int32_t GetHostResponse::cmdid() const {
  // @@protoc_insertion_point(field_get:rins.GetHostResponse.cmdid)
  return _internal_cmdid();
}
inline void GetHostResponse::_internal_set_cmdid(int32_t value) {
  
  _impl_.cmdid_ = value;
}
inline void GetHostResponse::set_cmdid(int32_t value) {
  _internal_set_cmdid(value);
  // @@protoc_insertion_point(field_set:rins.GetHostResponse.cmdid)
}

// int32 retcode = 4;
inline void GetHostResponse::clear_retcode() {
  _impl_.retcode_ = 0;
}
inline int32_t GetHostResponse::_internal_retcode() const {
  return _impl_.retcode_;
}
inline int32_t GetHostResponse::retcode() const {
  // @@protoc_insertion_point(field_get:rins.GetHostResponse.retcode)
  return _internal_retcode();
}
inline void GetHostResponse::_internal_set_retcode(int32_t value) {
  
  _impl_.retcode_ = value;
}
inline void GetHostResponse::set_retcode(int32_t value) {
  _internal_set_retcode(value);
  // @@protoc_insertion_point(field_set:rins.GetHostResponse.retcode)
}

// .rins.HostInfo host = 5;
inline bool GetHostResponse::_internal_has_host() const {
  return this != internal_default_instance() && _impl_.host_ != nullptr;
}
inline bool GetHostResponse::has_host() const {
  return _internal_has_host();
}
inline void GetHostResponse::clear_host() {
  if (GetArenaForAllocation() == nullptr && _impl_.host_ != nullptr) {
    delete _impl_.host_;
  }
  _impl_.host_ = nullptr;
}
inline const ::rins::HostInfo& GetHostResponse::_internal_host() const {
  const ::rins::HostInfo* p = _impl_.host_;
  return p != nullptr ? *p : reinterpret_cast<const ::rins::HostInfo&>(
      ::rins::_HostInfo_default_instance_);
}
inline const ::rins::HostInfo& GetHostResponse::host() const {
  // @@protoc_insertion_point(field_get:rins.GetHostResponse.host)
  return _internal_host();
}
inline void GetHostResponse::unsafe_arena_set_allocated_host(
    ::rins::HostInfo* host) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.host_);
  }
  _impl_.host_ = host;
  if (host) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rins.GetHostResponse.host)
}
inline ::rins::HostInfo* GetHostResponse::release_host() {
  
  ::rins::HostInfo* temp = _impl_.host_;
  _impl_.host_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rins::HostInfo* GetHostResponse::unsafe_arena_release_host() {
  // @@protoc_insertion_point(field_release:rins.GetHostResponse.host)
  
  ::rins::HostInfo* temp = _impl_.host_;
  _impl_.host_ = nullptr;
  return temp;
}
inline ::rins::HostInfo* GetHostResponse::_internal_mutable_host() {
  
  if (_impl_.host_ == nullptr) {
    auto* p = CreateMaybeMessage<::rins::HostInfo>(GetArenaForAllocation());
    _impl_.host_ = p;
  }
  return _impl_.host_;
}
inline ::rins::HostInfo* GetHostResponse::mutable_host() {
  ::rins::HostInfo* _msg = _internal_mutable_host();
  // @@protoc_insertion_point(field_mutable:rins.GetHostResponse.host)
  return _msg;
}
inline void GetHostResponse::set_allocated_host(::rins::HostInfo* host) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.host_;
  }
  if (host) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(host);
    if (message_arena != submessage_arena) {
      host = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, host, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.host_ = host;
  // @@protoc_insertion_point(field_set_allocated:rins.GetHostResponse.host)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace rins

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::rins::MessageID> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::rins::MessageID>() {
  return ::rins::MessageID_descriptor();
}
template <> struct is_proto_enum< ::rins::RinsRetCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::rins::RinsRetCode>() {
  return ::rins::RinsRetCode_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_rins_2eproto
